spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
  datasource:
    url: jdbc:postgresql://${UMS_DB_HOST}:${UMS_DB_PORT}/${UMS_DB_NAME}
    username: ${UMS_DB_USER_NAME}
    password: ${UMS_DB_PASSWORD}
    driver: org.postgresql.Driver